# Generated by Django 5.2.8 on 2025-11-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the task", max_length=255),
                ),
                ("due_date", models.DateField(help_text="Date when task is due")),
                (
                    "importance",
                    models.IntegerField(
                        default=5, help_text="Importance rating from 1-10"
                    ),
                ),
                (
                    "estimated_hours",
                    models.FloatField(
                        default=2, help_text="Estimated hours to complete"
                    ),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of task IDs this task depends on",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this task was created"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
